Repository Graduate-or-die/Graduate-or-die-server, pull requests merged in 2025-07, with the labels that each got.

#2 [Docs] 이슈/PR 템플릿 생성
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/ISSUE_TEMPLATE/refactor-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .idea/.gitignore
  .idea/Graduate-or-die-server.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: 🗒️ Docs

#8 feat: 유저 도메인 구현
  pome-server/src/main/java/server/pome/global/domain/User.java
Labels: ✨ Feature, p1, 🥐현서

#12 feat: 포트폴리오 TypeEnum
  pome-server/src/main/java/server/pome/global/domain/Portfolio.java
  pome-server/src/main/java/server/pome/global/exception/BaseResponseStatus.java
  pome-server/src/main/java/server/pome/portfolio/type/TypeEnum.java
Labels: ✨ Feature, p1, 🍦해림
